"""Initial migration

Revision ID: adf231a4d631
Revises: 
Create Date: 2024-08-04 20:47:16.891465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adf231a4d631'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('allure_tekg', sa.Column('links', postgresql.JSONB, nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allure_tekg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steps', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('parameters',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('attachments',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('statusdetails',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('labels',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('links')

    # ### end Alembic commands ###
