"""Initial migration.

Revision ID: c062cebb0cf2
Revises: 
Create Date: 2024-08-04 12:51:13.244927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c062cebb0cf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allure_result',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('historyId', sa.String(), nullable=False),
    sa.Column('fullName', sa.String(), nullable=False),
    sa.Column('labels', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('statusDetails', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('start', sa.BigInteger(), nullable=False),
    sa.Column('stop', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allure_result')
    # ### end Alembic commands ###
